### ISSUE TITLE
Context to the "from our home" phrase

### ISSUE THREAD

**Issue by Rijgersberg** [steventroughtonsmith/broadcasts-localization#14]
I was having some difficulty translating the phrase "If you'd like, we have some preset stations _from our home_ that we can start your library with."

Are you referring to the literal home of the creators of the app (being you)? Or is it more of a reference to the way restaurants refer to specialities on their menu as "from the house"/"_à la maison_"?

The difference has implications for the translation.

**Comment by chhdamian** [comment]
In the polish translation, I changed it to "from Ireland" as it may not be obvious to the user what "our home" is.

**Comment by atnbueno** [comment]
Same. In the Spanish and Catalan translations I used the equivalent to "from our country".

**Comment by steventroughtonsmith** [comment]
‘From Ireland’ or ‘from our country’ are totally fine. If there’s a non-literal translation that means the same thing but sounds better, that would be fine too, as long as the size of the paragraph doesn’t change dramatically. Thanks!
